# Generated by Django 4.1.2 on 2022-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tweet_tweet_tweet_alter_tweet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
